services:
  - type: web
    name: devboard-backend
    env: docker
    repo: https://github.com/prateek54353/devboard-backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: devboard-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: HUGGINGFACE_API_TOKEN
        sync: false

databases:
  - name: devboard-db
    plan: free